services:
  - type: web
    name: youtube-transcript-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:10000
    autoDeploy: true
    envVars: []
